"""
Django settings for rd1web project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Import configuration from local_config
try:
    from pxe.local_config import (
        DATABASE_CONFIG,
        REDIS_HOST,
        REDIS_PORT,
        SECRET_KEY as LOCAL_SECRET_KEY,
        TIME_ZONE as LOCAL_TIME_ZONE,
        DEBUG as LOCAL_DEBUG,
        WEB_APP_PORT,
    )
    # Extract host IP from DATABASE_CONFIG
    host_ip = DATABASE_CONFIG['HOST']
    # Use local_config DEBUG if environment variable not set
    DEBUG = os.environ.get("DJANGO_DEBUG") == "1" if os.environ.get("DJANGO_DEBUG") else LOCAL_DEBUG
except ImportError:
    # Fallback to defaults if local_config doesn't exist
    from pxe.remote_config import remote_dict
    host_ip = remote_dict['us_b3'].host.split('@')[-1] if '@' in remote_dict['us_b3'].host else remote_dict['us_b3'].host
    DEBUG = os.environ.get("DJANGO_DEBUG") == "1"
    DATABASE_CONFIG = {
        'NAME': 'pxe_db',
        'USER': 'devin',
        'PASSWORD': 'devin123',
        'HOST': host_ip,
        'PORT': '5432',
    }
    REDIS_HOST = 'localhost'
    REDIS_PORT = 6379
    LOCAL_SECRET_KEY = 'django-insecure-(oql-%h*1h4%2+1-s&vkc+ls*4+l&atr*+(hajf)l4q76rf_ay'
    LOCAL_TIME_ZONE = 'America/Los_Angeles'
    WEB_APP_PORT = 5003



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = LOCAL_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

ALLOWED_HOSTS = ['*']  # Allow all IP addresses to access

CSRF_TRUSTED_ORIGINS = [
    f"http://{host_ip}:{WEB_APP_PORT}"
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'django_redis',  # For Redis caching
    'pxe',
    'authentication',
]

MIDDLEWARE = [
    'authentication.connection_middleware.DBConnectionMiddleware',  # Explicitly close DB connections
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'authentication.optimized_middleware.OptimizedAuthenticationMiddleware', # Custom auth
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'authentication.optimized_middleware.OptimizedUserActivityMiddleware',
    'authentication.optimized_middleware.OptimizedUserSessionMiddleware',
]

ROOT_URLCONF = 'rd1web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rd1web.wsgi.application'
ASGI_APPLICATION = 'rd1web.asgi.application'

# Channels configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# ASGI/Daphne timeout configurations for better file serving
ASGI_APPLICATION_CLOSE_TIMEOUT = 60  # Allow 60 seconds for apps to close
ASGI_HTTP_TIMEOUT = 600  # Allow 10 minutes for HTTP requests (large files)
ASGI_WEBSOCKET_HANDSHAKE_TIMEOUT = 10  # WebSocket handshake timeout


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DATABASE_CONFIG['NAME'],
        'USER': DATABASE_CONFIG['USER'],
        'PASSWORD': DATABASE_CONFIG['PASSWORD'],
        'HOST': DATABASE_CONFIG['HOST'],
        'PORT': DATABASE_CONFIG['PORT'],
        'CONN_MAX_AGE': 600,  # Connection pooling for 10 minutes
    }
}

# Redis Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            'IGNORE_EXCEPTIONS': True,
        },
        'KEY_PREFIX': 'rd1web',
        'TIMEOUT': 300,  # 5 minutes default
        'VERSION': 1,
    }
}

# Use Redis for session storage for better performance
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = LOCAL_TIME_ZONE

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Static files will be collected here for production
STATIC_ROOT = os.path.join(BASE_DIR.parent, 'staticfiles')

# Redis Configuration (imported from local_config)
# REDIS_HOST and REDIS_PORT are already imported at top

# Celery Configuration
CELERY_BROKER_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/0'
CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:{REDIS_PORT}/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 300  # 5 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 240  # 4 minutes
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Security settings for proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/auth/login/'

# Additional session settings
SESSION_SAVE_EVERY_REQUEST = False  # Only save when modified for performance
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True  # Security setting

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'pxe': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Increase the maximum number of fields in forms to handle Django admin with many permissions
DATA_UPLOAD_MAX_NUMBER_FIELDS = 5000
