# Generated by Django 5.2.1 on 2025-06-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='success',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
