# Generated by Django 5.2.1 on 2025-07-01 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_performance_indexes'),
        ('authentication', '0003_alter_useractivity_user'),
    ]

    operations = [
    ]
