# Generated by Django 5.2.1 on 2025-07-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_merge_20250701_0016'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='authenticat_user_id_6e9168_idx',
            old_name='auth_useractivity_user_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='authenticat_action_0cd4a2_idx',
            old_name='auth_useractivity_action_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='authenticat_timesta_f33446_idx',
            old_name='auth_useractivity_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='authenticat_user_id_f99cb4_idx',
            old_name='auth_useractivity_user_action_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='authenticat_session_e3761b_idx',
            old_name='auth_usersession_session_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='authenticat_user_id_f427c8_idx',
            old_name='auth_usersession_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='authenticat_last_ac_04a1e9_idx',
            old_name='auth_usersession_last_activity_idx',
        ),
        migrations.RenameIndex(
            model_name='userstats',
            new_name='authenticat_user_id_90730c_idx',
            old_name='auth_userstats_user_idx',
        ),
        migrations.RenameIndex(
            model_name='userstats',
            new_name='authenticat_last_ac_66baa3_idx',
            old_name='auth_userstats_last_activity_idx',
        ),
    ]
