# Generated by Django 5.2.1 on 2026-04-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_useractivity_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('page_view', 'Page View'), ('ai_analyzer', 'AI Analyzer'), ('ai_summary', 'AI Summary'), ('pxe_config', 'PXE Configuration'), ('system_view', 'System Details View'), ('ipmitool_use', 'IPMI Tool Usage'), ('log_view', 'Log File View'), ('file_view', 'File View'), ('kvm_access', 'KVM Access'), ('sol_access', 'SOL Access'), ('password_change', 'Password Change'), ('profile_view', 'Profile View'), ('admin_access', 'Admin Panel Access'), ('rma_pxe', 'RMA PXE Configuration'), ('rma_permission', 'RMA Permission management'), ('rma_log_view', 'RMA Log View'), ('rma_file_view', 'RMA File View'), ('mac_ip_view', 'MAC-IP Scan View'), ('firmware_inventory_view', 'Firmware Inventory View'), ('firmware_inventory_upload', 'Firmware Inventory Upload'), ('firmware_inventory_delete', 'Firmware Inventory Delete')], max_length=30),
        ),
    ]
