# Generated by Django 5.2.1 on 2025-06-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArpScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('mac_address', models.CharField(max_length=18)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ip_address'],
            },
        ),
    ]
