# Generated by Django 5.2.1 on 2025-06-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0002_arpscanresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arpscanresult',
            options={'ordering': ['subnet_source', 'ip_address']},
        ),
        migrations.AddField(
            model_name='arpscanresult',
            name='scan_interface',
            field=models.CharField(default='eno1', help_text='Network interface used for scanning', max_length=20),
        ),
        migrations.AddField(
            model_name='arpscanresult',
            name='subnet_source',
            field=models.CharField(default='local', help_text='Source subnet: local, remote, etc.', max_length=50),
        ),
    ]
