# Generated by Django 5.2.1 on 2025-06-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0003_alter_arpscanresult_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=255, unique=True)),
                ('mac_address', models.CharField(db_index=True, max_length=32)),
                ('formatted_mac', models.CharField(max_length=32)),
                ('system_type', models.CharField(choices=[('burnin', 'BurnIn Tests'), ('dc', 'DC Tests'), ('ac', 'AC Tests'), ('other', 'Other'), ('archive', 'Archived')], max_length=20)),
                ('status', models.CharField(choices=[('online', 'Online'), ('recent', 'Recent'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('activity_status', models.CharField(choices=[('online', 'Online'), ('recent', 'Recent'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('bmc_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('lan_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('current_test', models.CharField(blank=True, max_length=255, null=True)),
                ('test_progress', models.JSONField(blank=True, default=dict)),
                ('test_details', models.JSONField(blank=True, default=dict)),
                ('sysconfig', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['system_type', '-last_updated'], name='pxe_systemm_system__af93d9_idx'), models.Index(fields=['is_archived', '-last_updated'], name='pxe_systemm_is_arch_a00615_idx'), models.Index(fields=['activity_status'], name='pxe_systemm_activit_1aada1_idx')],
            },
        ),
    ]
