# Generated by Django 5.2.1 on 2025-07-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0004_systemmetadata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemMetadata',
        ),
    ]
