# Generated by Django 5.2.1 on 2025-07-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0006_delete_systemmetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arpscanresult',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterUniqueTogether(
            name='arpscanresult',
            unique_together={('ip_address', 'subnet_source')},
        ),
    ]
