# Generated by Django 5.2.1 on 2025-07-11 01:04

from django.db import migrations, models

def cleanup_duplicate_macs(apps, schema_editor):
    """
    Find and remove duplicate ArpScanResult entries based on mac_address and subnet_source,
    keeping only the most recently seen entry for each duplicate pair.
    """
    ArpScanResult = apps.get_model('pxe', 'ArpScanResult')
    db_alias = schema_editor.connection.alias
    
    # Find all MAC addresses that have duplicates within the same subnet
    duplicates = (
        ArpScanResult.objects.using(db_alias)
        .values('mac_address', 'subnet_source')
        .annotate(count=models.Count('id'))
        .filter(count__gt=1)
    )
    
    # For each set of duplicates, keep only the most recent entry and delete the rest
    for dup in duplicates:
        # Get IDs of all but the most recently seen entry
        ids_to_delete = list(
            ArpScanResult.objects.using(db_alias)
            .filter(
                mac_address=dup['mac_address'],
                subnet_source=dup['subnet_source']
            )
            .order_by('-last_seen')
            .values_list('id', flat=True)[1:]
        )
        
        # Bulk delete the older, duplicate entries
        if ids_to_delete:
            ArpScanResult.objects.using(db_alias).filter(id__in=ids_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0007_alter_arpscanresult_ip_address_and_more'),
    ]

    operations = [
        # Step 1: Clean up duplicate data before applying the constraint
        migrations.RunPython(cleanup_duplicate_macs, reverse_code=migrations.RunPython.noop),
        
        # Step 2: Apply the unique constraint
        migrations.AlterUniqueTogether(
            name='arpscanresult',
            unique_together={('mac_address', 'subnet_source')},
        ),
    ]
