# Generated by Django 5.2.1 on 2025-09-19 22:39

import pxe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0008_alter_arpscanresult_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RmaTestingDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmc_mac', models.CharField(help_text='BMC MAC address (format: xx:xx:xx:xx:xx:xx)', max_length=17, unique=True, validators=[pxe.models.validate_mac_address], verbose_name='BMC MAC Address')),
                ('bmc_ip', models.GenericIPAddressField(help_text='BMC IP address', verbose_name='BMC IP Address')),
                ('bmc_password', models.CharField(help_text='BMC unique password', max_length=255, verbose_name='BMC Password')),
                ('lan0_mac', models.CharField(help_text='LAN0 MAC address (format: xx:xx:xx:xx:xx:xx)', max_length=17, validators=[pxe.models.validate_mac_address], verbose_name='LAN0 MAC Address')),
                ('lan1_mac', models.CharField(help_text='LAN1 MAC address (format: xx:xx:xx:xx:xx:xx)', max_length=17, validators=[pxe.models.validate_mac_address], verbose_name='LAN1 MAC Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RMA Testing DB Entry',
                'verbose_name_plural': 'RMA Testing DB Entries',
                'ordering': ['bmc_mac'],
                'permissions': [('can_access_rma_testing_db', 'Can access RMA Testing DB')],
            },
        ),
    ]
