# Generated by Django 5.2.1 on 2025-09-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0009_rmatestingdb'),
    ]

    operations = [
    ]
