# Generated by Django 5.2.1 on 2025-09-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0010_auto_20250919_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmatestingdb',
            name='golden_number',
            field=models.CharField(blank=True, default='', help_text='Golden Number identifier', max_length=100, verbose_name='Golden Number'),
        ),
    ]
