# Generated by Django 5.2.1 on 2025-09-23 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0011_rmatestingdb_golden_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pxeentry',
            options={'permissions': [('can_use_dashboard', 'Can use dashboard and overview'), ('can_use_system_management', 'Can use system management features'), ('can_use_tools', 'Can use tools and utilities'), ('can_view_rma_logs', 'Can view RMA logs'), ('can_access_rma_pxe', 'Can access RMA PXE management')]},
        ),
    ]
