# Generated by Django 5.2.1 on 2025-09-23 23:02

from django.db import migrations
from django.contrib.auth.models import User, Permission
from django.contrib.contenttypes.models import ContentType


def grant_default_permissions_to_existing_users(apps, schema_editor):
    """Grant default permissions to all existing users"""
    
    # Get the PxeEntry model and content type
    PxeEntry = apps.get_model('pxe', 'PxeEntry')
    content_type = ContentType.objects.get_for_model(PxeEntry)
    
    # Define default permissions that should be auto-granted
    default_permissions = [
        'can_use_dashboard',
        'can_use_system_management', 
        'can_use_tools',
        'can_view_rma_logs',
    ]
    
    # Grant default permissions to all existing users
    for user in User.objects.all():
        for perm_codename in default_permissions:
            try:
                permission = Permission.objects.get(
                    content_type=content_type,
                    codename=perm_codename
                )
                user.user_permissions.add(permission)
                print(f"Granted permission '{perm_codename}' to user '{user.username}'")
            except Permission.DoesNotExist:
                print(f"Warning: Permission '{perm_codename}' not found")


def reverse_grant_default_permissions(apps, schema_editor):
    """Remove default permissions from users (reverse operation)"""
    
    # Get the PxeEntry model and content type
    PxeEntry = apps.get_model('pxe', 'PxeEntry')
    content_type = ContentType.objects.get_for_model(PxeEntry)
    
    # Define default permissions to remove
    default_permissions = [
        'can_use_dashboard',
        'can_use_system_management', 
        'can_use_tools',
        'can_view_rma_logs',
    ]
    
    # Remove default permissions from all users
    for user in User.objects.all():
        for perm_codename in default_permissions:
            try:
                permission = Permission.objects.get(
                    content_type=content_type,
                    codename=perm_codename
                )
                user.user_permissions.remove(permission)
                print(f"Removed permission '{perm_codename}' from user '{user.username}'")
            except Permission.DoesNotExist:
                print(f"Warning: Permission '{perm_codename}' not found")


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0012_add_permissions'),
    ]

    operations = [
        migrations.RunPython(
            grant_default_permissions_to_existing_users,
            reverse_grant_default_permissions
        ),
    ]
