# Generated by Django 5.2.1 on 2025-10-01 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0015_alter_pxeentry_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rmatestingdb',
            options={'ordering': ['bmc_mac'], 'permissions': [('can_access_rma_testing_db', 'Can access RMA Testing DB'), ('can_force_unlink_golden', 'Can force unlink any golden number')], 'verbose_name': 'RMA Testing DB Entry', 'verbose_name_plural': 'RMA Testing DB Entries'},
        ),
        migrations.AddField(
            model_name='rmatestingdb',
            name='linked_user',
            field=models.ForeignKey(blank=True, help_text='User currently linked to this golden number', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_golden_numbers', to=settings.AUTH_USER_MODEL, verbose_name='Linked User'),
        ),
    ]
