# Generated by Django 5.2.1 on 2025-10-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0016_alter_rmatestingdb_options_rmatestingdb_linked_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmatestingdb',
            name='last_tester',
            field=models.CharField(blank=True, help_text='Last user who was linked to this golden number', max_length=150, null=True, verbose_name='Last Tester'),
        ),
    ]
