# Generated by Django 5.2.1 on 2025-10-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0017_rmatestingdb_last_tester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pxeentry',
            options={'permissions': [('can_use_dashboard', 'Can use dashboard and overview'), ('can_use_system_management', 'Can use system management features'), ('can_use_tools', 'Can use tools and utilities'), ('can_view_rma_logs', 'Can view RMA logs'), ('can_view_rma_statistics', 'Can view RMA statistics'), ('can_access_rma_pxe', 'Can access RMA PXE management'), ('can_access_rma_dhcp_leases', 'Can access RMA DHCP Leases')]},
        ),
        migrations.CreateModel(
            name='RmaTestStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_name', models.CharField(help_text='RMA directory name (e.g., 1660224656070_XD250311087)', max_length=255, unique=True, verbose_name='Directory Name')),
                ('base_sn', models.CharField(help_text='Base serial number parsed from directory name', max_length=100, verbose_name='Base SN')),
                ('rma_number', models.CharField(help_text='RMA number parsed from directory name', max_length=100, verbose_name='RMA Number')),
                ('gpu_model', models.CharField(default='Unknown', help_text='GPU model from sys_info.txt (e.g., H100, A100)', max_length=100, verbose_name='GPU Model')),
                ('test_date', models.DateTimeField(db_index=True, help_text='Directory modification time for time grouping', verbose_name='Test Date')),
                ('test_results', models.JSONField(default=dict, help_text='Test results: {gpu_detection: pass/fail, ecc_error: pass/fail, ...}', verbose_name='Test Results')),
                ('file_mtime', models.FloatField(help_text='test_results.log file modification time for change detection', verbose_name='File Mtime')),
                ('last_scanned', models.DateTimeField(auto_now=True, help_text='When this directory was last scanned', verbose_name='Last Scanned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RMA Test Statistic',
                'verbose_name_plural': 'RMA Test Statistics',
                'ordering': ['-test_date'],
                'indexes': [models.Index(fields=['test_date'], name='pxe_rmatest_test_da_5202a6_idx'), models.Index(fields=['gpu_model'], name='pxe_rmatest_gpu_mod_f73330_idx'), models.Index(fields=['test_date', 'gpu_model'], name='pxe_rmatest_test_da_a2e5d2_idx')],
            },
        ),
    ]
