# Generated by Django 5.2.1 on 2025-10-20 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0018_alter_pxeentry_options_rmateststatistic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pxeentry',
            options={'permissions': [('can_use_dashboard', 'Can use dashboard and overview'), ('can_use_system_management', 'Can use system management features'), ('can_use_tools', 'Can use tools and utilities'), ('can_view_rma_logs', 'Can view RMA logs'), ('can_view_rma_statistics', 'Can view RMA statistics'), ('can_access_rma_pxe', 'Can access RMA PXE management'), ('can_access_rma_dhcp_leases', 'Can access RMA DHCP Leases'), ('can_access_firmware_inventory', 'Can access Firmware Inventory')]},
        ),
        migrations.CreateModel(
            name='FirmwareFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('H100_AC', 'H100_AC'), ('H100_LC', 'H100_LC'), ('H200_AC', 'H200_AC'), ('H200_LC', 'H200_LC'), ('B200_AC', 'B200_AC'), ('B200_LC', 'B200_LC'), ('B300_AC', 'B300_AC'), ('B300_LC', 'B300_LC')], help_text='Product type (e.g., H100_AC, B200_LC)', max_length=20, verbose_name='Product Type')),
                ('eco_number', models.CharField(help_text='ECO number (free text)', max_length=100, verbose_name='ECO Number')),
                ('file_type', models.CharField(choices=[('GPU', 'GPU'), ('retimer_0', 'Retimer 0'), ('retimer_1', 'Retimer 1'), ('retimer_2', 'Retimer 2'), ('retimer_3', 'Retimer 3'), ('retimer_4', 'Retimer 4'), ('retimer_5', 'Retimer 5'), ('retimer_6', 'Retimer 6'), ('retimer_7', 'Retimer 7')], help_text='Firmware file type (GPU or retimer)', max_length=20, verbose_name='File Type')),
                ('filename', models.CharField(help_text='Stored filename', max_length=255, verbose_name='Filename')),
                ('file_path', models.CharField(help_text='Full path to the firmware file', max_length=512, verbose_name='File Path')),
                ('file_size', models.BigIntegerField(help_text='File size in bytes', verbose_name='File Size')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When this file was uploaded', verbose_name='Uploaded At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time', verbose_name='Updated At')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_firmware_files', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Firmware File',
                'verbose_name_plural': 'Firmware Files',
                'ordering': ['product_type', 'eco_number', 'file_type'],
                'indexes': [models.Index(fields=['product_type', 'eco_number'], name='pxe_firmwar_product_0bf40f_idx'), models.Index(fields=['uploaded_by'], name='pxe_firmwar_uploade_4a4fea_idx'), models.Index(fields=['uploaded_at'], name='pxe_firmwar_uploade_6372a2_idx')],
                'unique_together': {('product_type', 'eco_number', 'file_type')},
            },
        ),
    ]
