# Generated by Django 5.2.1 on 2025-10-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0019_alter_pxeentry_options_firmwarefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmwarefile',
            name='original_filename',
            field=models.CharField(blank=True, default='', help_text='Original uploaded filename', max_length=255, verbose_name='Original Filename'),
        ),
    ]
