# Generated by Django 5.2.1 on 2025-10-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0020_firmwarefile_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmateststatistic',
            name='directory_name',
            field=models.CharField(db_index=True, help_text='RMA directory name (e.g., 1660224656070_XD250311087)', max_length=255, verbose_name='Directory Name'),
        ),
        migrations.AlterUniqueTogether(
            name='rmateststatistic',
            unique_together={('directory_name', 'file_mtime')},
        ),
    ]
