# Generated by Django 5.2.1 on 2025-10-22 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0021_alter_rmateststatistic_directory_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pxeentry',
            options={'permissions': [('can_use_dashboard', 'Can use dashboard and overview'), ('can_use_system_management', 'Can use system management features'), ('can_use_tools', 'Can use tools and utilities'), ('can_view_rma_logs', 'Can view RMA logs'), ('can_view_rma_statistics', 'Can view RMA statistics'), ('can_access_rma_pxe', 'Can access RMA PXE management'), ('can_access_rma_general_test', 'Can access RMA General TEST'), ('can_access_rma_dhcp_leases', 'Can access RMA DHCP Leases'), ('can_access_firmware_inventory', 'Can access Firmware Inventory')]},
        ),
    ]
