# Generated by Django 5.2.1 on 2025-11-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0023_alter_pxeentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmatestingdb',
            name='linked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the golden number was linked to current user', null=True, verbose_name='Linked At'),
        ),
    ]
