# Generated by Django 5.2.1 on 2025-11-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0024_rmatestingdb_linked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pxeentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
