# Generated by Django 5.2.1 on 2025-12-09 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0025_pxeentry_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rmatestingdb',
            options={'ordering': ['bmc_mac'], 'permissions': [('can_access_rma_testing_db', 'Can access RMA Testing DB'), ('can_force_unlink_golden', 'Can force unlink any golden number'), ('can_view_golden_test_setting', 'Can view golden unit test setting')], 'verbose_name': 'RMA Testing DB Entry', 'verbose_name_plural': 'RMA Testing DB Entries'},
        ),
    ]
