# Generated by Django 5.2.1 on 2025-12-29 00:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0027_update_firmwarefile_paths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firmwarefile',
            options={'ordering': ['product_type', 'model', 'eco_number', 'file_type'], 'verbose_name': 'Firmware File', 'verbose_name_plural': 'Firmware Files'},
        ),
        migrations.RemoveIndex(
            model_name='firmwarefile',
            name='pxe_firmwar_product_0bf40f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='firmwarefile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='firmwarefile',
            name='model',
            field=models.CharField(blank=True, help_text='Device model (only for pcie product type)', max_length=100, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='firmwarefile',
            name='product_type',
            field=models.CharField(choices=[('H100_AC', 'H100_AC'), ('H100_LC', 'H100_LC'), ('H200_AC', 'H200_AC'), ('H200_LC', 'H200_LC'), ('B200_AC', 'B200_AC'), ('B200_LC', 'B200_LC'), ('B300_AC', 'B300_AC'), ('B300_LC', 'B300_LC'), ('pcie', 'pcie')], help_text='Product type (e.g., H100_AC, B200_LC, pcie)', max_length=20, verbose_name='Product Type'),
        ),
        migrations.AlterUniqueTogether(
            name='firmwarefile',
            unique_together={('product_type', 'model', 'eco_number', 'file_type')},
        ),
        migrations.AddIndex(
            model_name='firmwarefile',
            index=models.Index(fields=['product_type', 'model', 'eco_number'], name='pxe_firmwar_product_ab26e8_idx'),
        ),
    ]
