# Generated by Django 5.2.1 on 2026-02-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0029_rmagbdb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rmagbdb',
            options={'ordering': ['bmc_mac'], 'permissions': [('can_delete_rma_gb_db', 'Can delete RMA GB DB entries')], 'verbose_name': 'RMA GB DB Entry', 'verbose_name_plural': 'RMA GB DB Entries'},
        ),
    ]
