# Generated by Django 5.2.1 on 2026-02-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0030_add_delete_permission_rma_gb_db'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rmateststatistic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rmateststatistic',
            name='base',
            field=models.CharField(db_index=True, default='main', help_text="Statistics base source: 'main' for RMA_BASE_DIR, 'gb' for RMA_GB_BASE_DIR", max_length=10, verbose_name='Base'),
        ),
        migrations.AlterUniqueTogether(
            name='rmateststatistic',
            unique_together={('base', 'directory_name', 'file_mtime')},
        ),
        migrations.AddIndex(
            model_name='rmateststatistic',
            index=models.Index(fields=['base', 'test_date'], name='pxe_rmatest_base_dce228_idx'),
        ),
        migrations.AddIndex(
            model_name='rmateststatistic',
            index=models.Index(fields=['base', 'gpu_model'], name='pxe_rmatest_base_c19e61_idx'),
        ),
    ]
