# Generated by Django 5.2.1 on 2026-02-19 19:16

import django.db.models.deletion
import pxe.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0031_alter_rmateststatistic_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RmaPcieDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmc_mac', models.CharField(help_text='BMC MAC address (format: xx:xx:xx:xx:xx:xx)', max_length=17, unique=True, validators=[pxe.models.validate_mac_address], verbose_name='BMC MAC Address')),
                ('bmc_ip', models.GenericIPAddressField(help_text='BMC IP address', verbose_name='BMC IP Address')),
                ('bmc_password', models.CharField(help_text='BMC unique password', max_length=255, verbose_name='BMC Password')),
                ('lan0_mac', models.CharField(help_text='LAN0 MAC address (format: xx:xx:xx:xx:xx:xx)', max_length=17, validators=[pxe.models.validate_mac_address], verbose_name='LAN0 MAC Address')),
                ('lan1_mac', models.CharField(blank=True, default='', help_text='LAN1 MAC address (format: xx:xx:xx:xx:xx:xx)', max_length=17, validators=[pxe.models.validate_mac_address], verbose_name='LAN1 MAC Address')),
                ('golden_number', models.CharField(blank=True, default='', help_text='Golden Number identifier', max_length=100, verbose_name='Golden Number')),
                ('linked_at', models.DateTimeField(blank=True, help_text='Timestamp when the golden number was linked to current user', null=True, verbose_name='Linked At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_tester', models.CharField(blank=True, help_text='Last user who was linked to this golden number', max_length=150, null=True, verbose_name='Last Tester')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_user', models.ForeignKey(blank=True, help_text='User currently linked to this golden number', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_pcie_golden_numbers', to=settings.AUTH_USER_MODEL, verbose_name='Linked User')),
            ],
            options={
                'verbose_name': 'RMA PCIE DB Entry',
                'verbose_name_plural': 'RMA PCIE DB Entries',
                'ordering': ['bmc_mac'],
                'permissions': [('can_delete_rma_pcie_db', 'Can delete PCIE DB entries')],
            },
        ),
    ]
