# Generated by Django 5.2.1 on 2026-02-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0032_rmapciedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmatestingdb',
            name='is_golden',
            field=models.BooleanField(default=False, help_text='Mark this entry as a golden unit', verbose_name='Is Golden'),
        ),
    ]
