# Generated by Django 5.2.1 on 2026-03-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0033_add_rmatestingdb_is_golden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmwarefile',
            name='file_type',
            field=models.CharField(choices=[('GPU', 'GPU'), ('BIOS', 'BIOS'), ('retimer_0', 'Retimer 0'), ('retimer_1', 'Retimer 1'), ('retimer_2', 'Retimer 2'), ('retimer_3', 'Retimer 3'), ('retimer_4', 'Retimer 4'), ('retimer_5', 'Retimer 5'), ('retimer_6', 'Retimer 6'), ('retimer_7', 'Retimer 7')], help_text='Firmware file type (GPU or retimer)', max_length=20, verbose_name='File Type'),
        ),
        migrations.AlterField(
            model_name='firmwarefile',
            name='product_type',
            field=models.CharField(choices=[('H100_AC', 'H100_AC'), ('H100_LC', 'H100_LC'), ('H200_AC', 'H200_AC'), ('H200_LC', 'H200_LC'), ('B200_AC', 'B200_AC'), ('B200_LC', 'B200_LC'), ('B300_AC', 'B300_AC'), ('B300_LC', 'B300_LC'), ('GB300', 'GB300'), ('pcie', 'pcie')], help_text='Product type (e.g., H100_AC, B200_LC, pcie)', max_length=20, verbose_name='Product Type'),
        ),
    ]
