# Generated by Django 5.2.1 on 2026-04-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0034_add_gb300_bios_firmware_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pxeentry',
            options={'permissions': [('can_use_dashboard', 'Can use dashboard and overview'), ('can_use_system_management', 'Can use system management features'), ('can_use_tools', 'Can use tools and utilities'), ('can_view_rma_logs', 'Can view RMA logs'), ('can_view_rma_statistics', 'Can view RMA statistics'), ('can_view_rd1_statistics', 'Can view RD1 statistics'), ('can_access_rma_pxe', 'Can access RMA PXE management'), ('can_access_rma_general_test', 'Can access RMA General TEST'), ('can_view_rma_general_logs', 'Can view RMA General logs'), ('can_access_rma_dhcp_leases', 'Can access RMA DHCP Leases'), ('can_access_firmware_inventory', 'Can access Firmware Inventory')]},
        ),
        migrations.CreateModel(
            name='Rd1TestStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(db_index=True, default='main', help_text="Statistics base source: 'main' for RMA_BASE_DIR, 'gb' for RMA_GB_BASE_DIR", max_length=10, verbose_name='Base')),
                ('directory_name', models.CharField(db_index=True, help_text='RMA directory name (e.g., 1660224656070_XD250311087)', max_length=255, verbose_name='Directory Name')),
                ('base_sn', models.CharField(help_text='Base serial number parsed from directory name', max_length=100, verbose_name='Base SN')),
                ('rma_number', models.CharField(help_text='RMA number parsed from directory name', max_length=100, verbose_name='RMA Number')),
                ('gpu_model', models.CharField(default='Unknown', help_text='GPU model from sys_info.txt (e.g., H100, B200)', max_length=100, verbose_name='GPU Model')),
                ('test_date', models.DateTimeField(db_index=True, help_text='Directory modification time for time grouping', verbose_name='Test Date')),
                ('test_results', models.JSONField(default=dict, help_text='Strict test results: {gpu_detection, ecc_error, dcgm_test, dcgm_r4_test, fd2_test, fd2_items: {item: pass/fail}, agfhc_test}', verbose_name='Test Results')),
                ('file_mtime', models.FloatField(help_text='test_results.log file modification time for change detection', verbose_name='File Mtime')),
                ('last_scanned', models.DateTimeField(auto_now=True, help_text='When this directory was last scanned', verbose_name='Last Scanned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RD1 Test Statistic',
                'verbose_name_plural': 'RD1 Test Statistics',
                'ordering': ['-test_date'],
                'indexes': [models.Index(fields=['test_date'], name='pxe_rd1test_test_da_b33212_idx'), models.Index(fields=['gpu_model'], name='pxe_rd1test_gpu_mod_d836be_idx'), models.Index(fields=['test_date', 'gpu_model'], name='pxe_rd1test_test_da_04849e_idx'), models.Index(fields=['base', 'test_date'], name='pxe_rd1test_base_072c66_idx'), models.Index(fields=['base', 'gpu_model'], name='pxe_rd1test_base_1dfbfe_idx')],
                'unique_together': {('base', 'directory_name', 'file_mtime')},
            },
        ),
    ]
