# Generated by Django 5.2.1

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pxe', '0035_add_rd1_test_statistic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pxeentry',
            options={
                'permissions': [
                    ('can_use_dashboard', 'Can use dashboard and overview'),
                    ('can_use_system_management', 'Can use system management features'),
                    ('can_use_tools', 'Can use tools and utilities'),
                    ('can_view_rma_logs', 'Can view RMA logs'),
                    ('can_view_rma_statistics', 'Can view RMA statistics'),
                    ('can_view_rd1_statistics', 'Can view RD1 statistics'),
                    ('can_access_rma_pxe', 'Can access RMA PXE management'),
                    ('can_access_rma_general_test', 'Can access RMA General TEST'),
                    ('can_view_rma_general_logs', 'Can view RMA General logs'),
                    ('can_access_rma_dhcp_leases', 'Can access RMA DHCP Leases'),
                    ('can_access_firmware_inventory', 'Can access Firmware Inventory'),
                    ('can_manage_rma_permission', 'Can use RMA Permission page to assign RMA test access'),
                ]
            },
        ),
    ]
